# Generated by Django 4.1.4 on 2023-05-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('arabic', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
