# Generated by Django 4.1.4 on 2023-05-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_address_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='language',
            new_name='languages_label',
        ),
        migrations.AlterModelTable(
            name='languages_label',
            table='languages_label',
        ),
    ]
