# Generated by Django 4.1.4 on 2023-05-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_rename_language_languages_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
