# Generated by Django 4.1.4 on 2023-05-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0005_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address_type',
            new_name='packages',
        ),
        migrations.AlterModelTable(
            name='packages',
            table='packages',
        ),
    ]
