# Generated by Django 4.1.4 on 2023-05-12 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0007_rename_name_packages_package_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_name',
            field=models.CharField(choices=[('free', 'free'), ('basic', 'basic'), ('premimum', 'premimum')], default='free', max_length=50),
        ),
        migrations.CreateModel(
            name='user_membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterapp.packages')),
            ],
            options={
                'db_table': 'user_membership',
            },
        ),
    ]
