# Generated by Django 4.1.4 on 2023-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0009_user_membership_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('site_sub_title', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('map_link', models.TextField()),
                ('smtp_host', models.CharField(max_length=200)),
                ('smtp_username', models.CharField(max_length=200)),
                ('smtp_password', models.CharField(max_length=200)),
                ('smtp_port', models.CharField(max_length=200)),
                ('smtp_protocol', models.CharField(max_length=200)),
                ('smtp_from', models.CharField(max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField()),
                ('default_package', models.IntegerField()),
            ],
            options={
                'db_table': 'setting',
            },
        ),
    ]
