# Generated by Django 4.1.4 on 2023-05-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0010_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_membership',
            name='package',
        ),
        migrations.RemoveField(
            model_name='user_membership',
            name='user',
        ),
        migrations.DeleteModel(
            name='packages',
        ),
        migrations.DeleteModel(
            name='user_membership',
        ),
    ]
