# Generated by Django 4.1.4 on 2023-05-13 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0011_remove_user_membership_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('individual_price', models.IntegerField()),
                ('business_price', models.IntegerField()),
                ('individual_discount', models.IntegerField()),
                ('business_discount', models.ImageField(upload_to='')),
                ('validity', models.IntegerField()),
                ('max_contracts', models.IntegerField()),
                ('max_contacts', models.IntegerField()),
                ('descriptions', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
    ]
