# Generated by Django 4.1.4 on 2023-06-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0014_alter_usermembership_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='usermembership',
            old_name='user_id',
            new_name='user',
        ),
    ]
