# Generated by Django 4.1.4 on 2023-06-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0015_rename_package_id_usermembership_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages_label',
            old_name='label',
            new_name='code',
        ),
    ]
