# Generated by Django 4.1.4 on 2023-07-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0016_rename_label_languages_label_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business')], default='Individual', max_length=100)),
                ('membership_name', models.CharField(max_length=100)),
                ('membership_amount', models.IntegerField(null=True)),
                ('discount_type', models.BooleanField(default=False, null=True)),
                ('discount_rate', models.IntegerField(null=True)),
                ('discount_price', models.IntegerField(null=True)),
                ('payment_gateway_kne', models.BooleanField(default=False, null=True)),
                ('payment_gateway_cb_card', models.BooleanField(default=False, null=True)),
                ('payment_gateway_gp', models.BooleanField(default=False, null=True)),
                ('payment_gateway_ap', models.BooleanField(default=False, null=True)),
                ('number_of_contract', models.IntegerField(null=True)),
                ('number_of_parties', models.IntegerField(null=True)),
                ('Chat_between_Parties', models.BooleanField(default=False, null=True)),
                ('edit_templates', models.BooleanField(default=False, null=True)),
                ('address_book', models.BooleanField(default=False, null=True)),
                ('create_blank_contract', models.BooleanField(default=False, null=True)),
                ('upload_contract', models.BooleanField(default=False, null=True)),
                ('view_log', models.BooleanField(default=False, null=True)),
                ('view_contract_storage', models.BooleanField(default=False, null=True)),
                ('free_sign_up', models.BooleanField(default=False, null=True)),
                ('private_or_not', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
    ]
