# Generated by Django 4.1.4 on 2023-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0017_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='day_availability',
            field=models.IntegerField(null=True),
        ),
    ]
