# Generated by Django 4.1.4 on 2023-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0018_membership_day_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='package_price',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='ref_number',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='tr_number',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user_type',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='coupen_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='discount_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='usermembership',
            table=None,
        ),
    ]
