# Generated by Django 4.1.4 on 2023-07-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0019_remove_usermembership_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='package',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterapp.membership'),
        ),
    ]
