# Generated by Django 4.1.4 on 2023-07-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterapp', '0020_remove_usermembership_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='contract_histroy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
