# Generated by Django 4.1.4 on 2023-07-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0022_contract_histroy_action_info_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermembership',
            table='user_membership',
        ),
    ]
