# Generated by Django 4.1.4 on 2023-07-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0023_alter_usermembership_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract_histroy',
            table='contract_history',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
