# Generated by Django 4.1.4 on 2023-07-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0024_alter_contract_histroy_table_alter_payment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_amount',
            new_name='payment_amount',
        ),
    ]
