# Generated by Django 4.1.4 on 2023-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0025_rename_total_amount_payment_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_id',
            field=models.IntegerField(null=True),
        ),
    ]
