# Generated by Django 4.1.4 on 2023-07-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0026_payment_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
