# Generated by Django 4.1.4 on 2023-07-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0029_alter_payment_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
