# Generated by Django 4.1.4 on 2023-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0031_alter_usermembership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_histroy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
