# Generated by Django 4.1.4 on 2023-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0032_alter_contract_histroy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='edit_templates',
            new_name='add_free_premium_template',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='view_contract_storage',
            new_name='add_unlimited_templates',
        ),
        migrations.AddField(
            model_name='membership',
            name='free_contract_storage',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='free_template',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
