# Generated by Django 4.1.4 on 2023-07-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0034_alter_membership_membership_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='add_free_premium_template',
            new_name='free_premium_template',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='add_unlimited_templates',
            new_name='unlimited_templates',
        ),
    ]
