# Generated by Django 4.1.4 on 2023-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0037_rename_chat_between_parties_membership_chat_between_parties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
