# Generated by Django 4.1.4 on 2023-07-19 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0038_alter_membership_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=100, null=True)),
                ('coupon_code', models.CharField(max_length=50, null=True, unique=True)),
                ('limited_number_input', models.IntegerField(default=True, null=True)),
                ('limited_coupon_code', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('total_coupons', models.PositiveIntegerField(null=True)),
                ('used', models.PositiveIntegerField(null=True)),
                ('unused', models.PositiveIntegerField(null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('banner_image', models.ImageField(null=True, upload_to='coupon_banners/')),
                ('discount_details', models.TextField(null=True)),
                ('discount_type', models.CharField(max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('alert', models.BooleanField(null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('discount_for', models.CharField(max_length=100, null=True)),
                ('selected_users', models.CharField(max_length=100, null=True)),
                ('discount_for_user_type', models.IntegerField(null=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='inactive', max_length=255, null=True)),
            ],
        ),
    ]
