# Generated by Django 4.1.4 on 2023-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0039_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_for',
            field=models.CharField(choices=[('Membership', 'membership'), ('Contracts', 'contracts'), ('Users', 'users'), ('All', 'all')], max_length=255, null=True),
        ),
    ]
