# Generated by Django 4.1.4 on 2023-07-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0040_alter_coupon_discount_for'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table='coupon',
        ),
    ]
