# Generated by Django 4.1.4 on 2023-07-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0041_alter_coupon_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='limited_number_input',
            new_name='limited_coupon_per_Customer',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='limited_coupon_code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='unused',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active_status',
            field=models.CharField(choices=[('Inactive', 'inactive'), ('Active', 'active')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_for',
            field=models.CharField(choices=[('membership', 'Membership'), ('contracts', 'Contracts'), ('users', 'Users'), ('all', 'All')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Amount', 'amount'), ('Percentage', 'percentage')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='total_coupons',
            field=models.CharField(default='Unlimited', max_length=20, null=True),
        ),
    ]
