# Generated by Django 4.1.4 on 2023-07-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0042_rename_limited_number_input_coupon_limited_coupon_per_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_for_user_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
