# Generated by Django 4.1.4 on 2023-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0043_remove_coupon_discount_for_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
