# Generated by Django 4.1.4 on 2023-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0044_payment_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_enable', models.BooleanField(default=False, null=True)),
                ('individual_user', models.BooleanField(default=False, null=True)),
                ('business_user', models.BooleanField(default=False, null=True)),
                ('business_admin', models.BooleanField(default=False, null=True)),
                ('maintenance_mode_web_panel_image', models.ImageField(blank=True, null=True, upload_to='setting_pic')),
                ('maintenance_page_title', models.CharField(max_length=500, null=True)),
                ('maintenance_page_contain', models.CharField(max_length=800, null=True)),
                ('production_server_API_end_point', models.CharField(max_length=800, null=True)),
                ('pre_production_server_API_end_point', models.CharField(max_length=800, null=True)),
                ('test_server_API_end_point', models.CharField(max_length=800, null=True)),
                ('iphone_application_update', models.BooleanField(default=False, null=True)),
                ('iphone_update_mandatory', models.BooleanField(null=True)),
                ('iphone_current_version', models.CharField(max_length=100, null=True)),
                ('iphone_new_version', models.CharField(max_length=100, null=True)),
                ('android_application_update', models.BooleanField(default=False, null=True)),
                ('android_update_mandatory', models.BooleanField(default=False, null=True)),
                ('android_current_version', models.CharField(max_length=100, null=True)),
                ('android_new_version', models.CharField(max_length=500, null=True)),
                ('web_panel_header_logo', models.ImageField(blank=True, null=True, upload_to='setting_pic')),
                ('login_page_logo', models.ImageField(blank=True, null=True, upload_to='setting_pic')),
                ('webpanel_title_text', models.CharField(max_length=500, null=True)),
                ('webPanel_copyright_text', models.CharField(max_length=500, null=True)),
                ('contracts_price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('users_price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'general_settings',
            },
        ),
    ]
