# Generated by Django 4.1.4 on 2023-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0047_paymentmethod_membership_collaborative_editing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tothiq_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
