# Generated by Django 4.1.4 on 2023-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0048_payment_tothiq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tothiq_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
