# Generated by Django 4.1.4 on 2023-07-31 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0049_alter_payment_tothiq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='supertothiquser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/profile_pic/')),
                ('create_template', models.BooleanField(default=False, null=True)),
                ('edit_tempalte', models.BooleanField(default=False, null=True)),
                ('assign_custom_package', models.BooleanField(default=False, null=True)),
                ('activate_block_business_users', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', max_length=255, null=True)),
            ],
            options={
                'db_table': 'supertothiquser',
            },
        ),
    ]
