# Generated by Django 4.1.4 on 2023-07-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0050_supertothiquser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supertothiquser',
            new_name='tothiq_super_user',
        ),
        migrations.AlterModelTable(
            name='tothiq_super_user',
            table='tothiq_super_user',
        ),
    ]
