# Generated by Django 3.2.19 on 2023-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0051_rename_supertothiquser_tothiq_super_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref_number',
            new_name='ref_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_reference',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
