# Generated by Django 3.2.19 on 2023-08-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0052_auto_20230811_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_details',
            new_name='coupon_details',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_user_type',
            new_name='discount_for_user_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_details_arabic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_name_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
