# Generated by Django 3.2.19 on 2023-08-25 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0053_auto_20230824_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('browser_name', models.CharField(max_length=250, null=True)),
                ('Ip_address', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('activity_Type', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
    ]
