# Generated by Django 3.2.19 on 2023-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0057_contract_histroy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_histroy',
            name='action_info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
