# Generated by Django 3.2.19 on 2023-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0058_alter_contract_histroy_action_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages_label',
            name='arabic',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='languages_label',
            name='code',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='languages_label',
            name='english',
            field=models.TextField(max_length=100),
        ),
    ]
