# Generated by Django 3.2.19 on 2023-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0059_auto_20230901_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='fcm_server_key',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='myfatoorah_api_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='myfatoorah_api_url_key',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='payment_test_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_host_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_port',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_security',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_sender_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
