# Generated by Django 3.2.19 on 2023-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0061_membership_membership_name_arabic'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'country_currency',
            },
        ),
    ]
