# Generated by Django 3.2.19 on 2023-09-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0062_country_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_currency',
            name='currency_code',
        ),
    ]
