# Generated by Django 3.2.19 on 2023-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0064_rename_country_currency_countrycurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality_type',
            name='name_arabic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
