# Generated by Django 3.2.19 on 2023-09-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0065_nationality_type_name_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages_label',
            name='arabic',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
