# Generated by Django 3.2.19 on 2023-09-20 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0066_alter_languages_label_arabic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_code', models.CharField(db_index=True, max_length=100)),
                ('notification_subject', models.CharField(db_index=True, max_length=100)),
                ('notification_subject_arabic', models.CharField(db_index=True, max_length=100, null=True)),
                ('notification_content', models.TextField()),
                ('notification_content_arabic', models.TextField(null=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In Active'), ('delete', 'Delete')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
    ]
