# Generated by Django 3.2.19 on 2023-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0067_notificationtemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='login_page_logo_arabic',
            field=models.ImageField(blank=True, null=True, upload_to='setting_pic'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='web_panel_header_logo_arabic',
            field=models.ImageField(blank=True, null=True, upload_to='setting_pic'),
        ),
    ]
