# Generated by Django 3.2.19 on 2023-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0068_auto_20230926_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='free_premium_template',
            new_name='basic_template',
        ),
        migrations.AddField(
            model_name='membership',
            name='contract_template',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='premium_template',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
