# Generated by Django 3.2.19 on 2023-09-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0069_auto_20230929_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='unlimited_templates',
        ),
    ]
