# Generated by Django 3.2.19 on 2023-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0070_remove_membership_unlimited_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='selected_users',
            field=models.TextField(null=True),
        ),
    ]
