# Generated by Django 3.2.19 on 2023-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0072_auto_20231016_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='value',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Price', 'fixed_price'), ('Percentage', 'percentage')], max_length=20, null=True),
        ),
    ]
