# Generated by Django 3.2.19 on 2023-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification_images/')),
                ('user_type', models.CharField(max_length=50)),
                ('user_ids', models.CharField(max_length=255)),
                ('schedule_datetime', models.DateTimeField()),
                ('push_status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'general_notification',
            },
        ),
    ]
