# Generated by Django 3.2.19 on 2023-08-14 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_code', models.CharField(max_length=100)),
                ('email_subject', models.CharField(max_length=100)),
                ('email_content', models.TextField()),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In Active'), ('delete', 'Delete')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'email_template',
            },
        ),
    ]
