# Generated by Django 3.2.19 on 2023-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0002_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_template',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
