# Generated by Django 3.2.19 on 2023-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0003_alter_email_template_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
