# Generated by Django 3.2.19 on 2023-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0004_email_template_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='email_subject_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalnotification',
            name='message_arabic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='generalnotification',
            name='title_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
