# Generated by Django 3.2.19 on 2023-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0006_generalnotification_notifications_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='email_content_arabic',
            field=models.TextField(null=True),
        ),
    ]
