# Generated by Django 3.2.19 on 2023-09-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0008_alternativelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternativeLink',
        ),
    ]
