# Generated by Django 4.1.4 on 2023-06-12 09:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='civil_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
