# Generated by Django 4.1.4 on 2023-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0007_addressbook_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='full_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
