# Generated by Django 4.1.4 on 2023-05-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rename_parent_folder_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='user_id',
            new_name='user',
        ),
    ]
