# Generated by Django 4.1.4 on 2023-05-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_rename_parent_id_folder_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
