# Generated by Django 4.1.4 on 2023-05-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_notification_user_id_alter_notification_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
    ]
