# Generated by Django 4.1.4 on 2023-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_remove_notification_is_active_notification_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
