# Generated by Django 4.1.4 on 2023-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_availability',
            field=models.CharField(default='', max_length=50),
        ),
    ]
