# Generated by Django 4.1.4 on 2023-05-12 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_categories_category_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=200)),
                ('template_availability', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
