# Generated by Django 4.1.4 on 2023-05-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
    ]
