# Generated by Django 4.1.4 on 2023-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_template_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_availability',
            field=models.CharField(choices=[('Free membership', 'Free membership'), ('Basic membership', 'Basic membership'), ('Premium membership', 'Premium membership')], default='', max_length=50),
        ),
    ]
