# Generated by Django 4.1.4 on 2023-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_alter_categories_category_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
