# Generated by Django 4.1.4 on 2023-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_categories_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_title',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='categories',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
