# Generated by Django 4.1.4 on 2023-05-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_rename_category_title_categories_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='premium',
        ),
    ]
