# Generated by Django 4.1.4 on 2023-05-16 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_remove_categories_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='authorised_person',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='template',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='template',
            name='contract_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='template',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='template',
            name='days',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='rate_amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
