# Generated by Django 4.1.4 on 2023-05-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_rename_days_template_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='authorised_person',
        ),
        migrations.RemoveField(
            model_name='template',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='contract_title',
        ),
        migrations.RemoveField(
            model_name='template',
            name='date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='day',
        ),
        migrations.RemoveField(
            model_name='template',
            name='rate_amount',
        ),
        migrations.RemoveField(
            model_name='template',
            name='time',
        ),
    ]
