# Generated by Django 4.1.4 on 2023-05-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_remove_template_authorised_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('contract_startdate', models.DateField()),
                ('contract_enddate', models.DateField()),
                ('contract_valuation', models.DecimalField(decimal_places=3, max_digits=500)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.categories')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.template')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
