# Generated by Django 4.1.4 on 2023-05-18 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='template',
        ),
        migrations.AddField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contracts',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
