# Generated by Django 4.1.4 on 2023-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_contracts_status_contracts_template_contract_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_party',
            name='party_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
