# Generated by Django 4.1.4 on 2023-05-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_contract_first_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_party',
            name='party_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='contract_first_party',
        ),
    ]
