# Generated by Django 4.1.4 on 2023-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_alter_contract_party_party_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_party',
            name='party_type',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], max_length=10),
        ),
    ]
