# Generated by Django 4.1.4 on 2023-05-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_alter_contract_party_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_party',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts'),
        ),
    ]
