# Generated by Django 4.1.4 on 2023-05-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0041_alter_contract_party_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.folder'),
        ),
    ]
