# Generated by Django 4.1.4 on 2023-05-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0043_rename_civil_id_contract_party_second_party_civil_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_party',
            name='party_type',
        ),
    ]
