# Generated by Django 4.1.4 on 2023-05-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_remove_contract_party_party_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='contract_enddate',
            new_name='contract_end_date',
        ),
        migrations.RenameField(
            model_name='contracts',
            old_name='contract_startdate',
            new_name='contract_start_date',
        ),
    ]
