# Generated by Django 4.1.4 on 2023-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_alter_contracts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.CharField(choices=[('used', 'Used'), ('draft', 'Draft'), ('under_review', 'Under Review'), ('ready', 'Ready'), ('signed', 'Signed'), ('rejected', 'Rejected'), ('deleted', 'Deleted'), ('cancelled', 'Cancelled')], default='draft', max_length=15),
        ),
    ]
