# Generated by Django 4.1.4 on 2023-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_alter_contracts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, upload_to='tothiq_pic'),
        ),
    ]
