# Generated by Django 4.1.4 on 2023-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_template_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='appendix',
            field=models.ImageField(blank=True, upload_to='tothiq_pic'),
        ),
    ]
