# Generated by Django 4.1.4 on 2023-06-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_alter_contracts_contract_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
