# Generated by Django 4.1.4 on 2023-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_party',
            name='first_party_civil_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
