# Generated by Django 4.1.4 on 2023-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0053_alter_contract_party_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_party',
            name='view_contract',
            field=models.BooleanField(default=False),
        ),
    ]
