# Generated by Django 4.1.4 on 2023-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0054_contract_party_view_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], max_length=100, null=True),
        ),
    ]
