# Generated by Django 3.2.19 on 2023-08-11 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0057_contracts_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_contract_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_person_sign', models.CharField(max_length=500)),
                ('first_party_type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], max_length=500)),
                ('first_party_name', models.CharField(max_length=500)),
                ('first_party_email', models.CharField(max_length=500)),
                ('second_party_type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], max_length=500)),
                ('second_party_name', models.CharField(max_length=500)),
                ('second_party_email', models.CharField(max_length=500)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_contracts_party',
            },
        ),
    ]
