# Generated by Django 3.2.19 on 2023-08-11 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0058_business_contract_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_contract_party',
            name='first_party_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_party_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business_contract_party',
            name='second_party_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_party_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
