# Generated by Django 3.2.19 on 2023-08-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0060_alter_business_contract_party_authorized_person_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_contract_party',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.contracts'),
        ),
    ]
