# Generated by Django 3.2.19 on 2023-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0061_business_contract_party_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_contract_party',
            name='first_party_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business_contract_party',
            name='first_party_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business_contract_party',
            name='second_party_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business_contract_party',
            name='second_party_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], max_length=500, null=True),
        ),
    ]
