# Generated by Django 3.2.19 on 2023-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0062_auto_20230816_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='template_availability',
        ),
        migrations.AddField(
            model_name='template',
            name='business_basic_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='business_free_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='business_premium_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='indvidual_basic_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='indvidual_free_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='indvidual_premium_template',
            field=models.BooleanField(default=False),
        ),
    ]
