# Generated by Django 3.2.19 on 2023-08-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0063_auto_20230817_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='indvidual_basic_template',
            new_name='individual_basic_template',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='indvidual_free_template',
            new_name='individual_free_template',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='indvidual_premium_template',
            new_name='individual_premium_template',
        ),
    ]
