# Generated by Django 3.2.19 on 2023-08-23 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0066_contracts_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_contract_party',
            name='authorized_person_sign',
        ),
        migrations.AddField(
            model_name='business_contract_party',
            name='authorized_person_sign',
            field=models.ManyToManyField(blank=True, related_name='authorized_person_sign', to=settings.AUTH_USER_MODEL),
        ),
    ]
