# Generated by Django 3.2.19 on 2023-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0070_auto_20230824_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='pin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
