# Generated by Django 3.2.19 on 2023-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0072_folder_folder_name_arabic'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description_arabic',
            field=models.TextField(null=True),
        ),
    ]
