# Generated by Django 3.2.19 on 2023-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0074_auto_20230907_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='arbitration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='jurisdiction',
            field=models.BooleanField(null=True),
        ),
    ]
