# Generated by Django 3.2.19 on 2023-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0075_auto_20230911_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='cancellation_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='delete_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
