# Generated by Django 4.1.4 on 2023-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0002_alter_business_admin_users_authorized_signatory_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_admin_users',
            name='business_contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
