# Generated by Django 4.1.4 on 2023-06-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0004_alter_business_admin_users_authorized_signatory_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business_admin_users',
            new_name='business_admin_profile',
        ),
        migrations.AlterModelTable(
            name='business_admin_profile',
            table='business_admin_profile',
        ),
    ]
