# Generated by Django 4.1.4 on 2023-06-19 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_admin', '0005_rename_business_admin_users_business_admin_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=500, null=True)),
                ('business_email_address', models.CharField(blank=True, max_length=500)),
                ('business_contact_number', models.IntegerField(blank=True, null=True)),
                ('extension_number', models.IntegerField(blank=True, null=True)),
                ('business_address', models.CharField(blank=True, max_length=500, null=True)),
                ('licence_expiry_date', models.DateField(blank=True, null=True)),
                ('authorized_signatory_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_info',
            },
        ),
        migrations.DeleteModel(
            name='business_admin_profile',
        ),
        migrations.CreateModel(
            name='business_users',
            fields=[
                ('business_id', models.OneToOneField(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business_admin.business_info')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
