# Generated by Django 4.1.4 on 2023-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0006_business_info_delete_business_admin_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='business_users',
            table='business_users',
        ),
    ]
