# Generated by Django 4.1.4 on 2023-06-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0009_business_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_users',
            name='department_id',
            field=models.OneToOneField(db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='business_admin.business_department'),
        ),
    ]
