# Generated by Django 4.1.4 on 2023-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0011_alter_business_info_business_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='authorized_signatory_image',
            field=models.ImageField(blank=True, null=True, upload_to='tothiq_pic'),
        ),
        migrations.AddField(
            model_name='business_info',
            name='licence_image',
            field=models.ImageField(blank=True, null=True, upload_to='tothiq_pic'),
        ),
    ]
