# Generated by Django 4.1.4 on 2023-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0012_business_info_authorized_signatory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', max_length=255, null=True),
        ),
    ]
