# Generated by Django 4.1.4 on 2023-06-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0013_business_info_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_info',
            name='user',
        ),
    ]
