# Generated by Django 4.1.4 on 2023-06-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0014_remove_business_info_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='business_users',
        ),
    ]
