# Generated by Django 4.1.4 on 2023-06-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0016_business_admin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
