# Generated by Django 4.1.4 on 2023-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0017_business_info_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
