# Generated by Django 4.1.4 on 2023-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0018_alter_business_info_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
