# Generated by Django 4.1.4 on 2023-06-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0020_remove_business_info_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
