# Generated by Django 4.1.4 on 2023-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0023_alter_business_info_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
