# Generated by Django 4.1.4 on 2023-06-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0024_alter_business_info_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
