# Generated by Django 4.1.4 on 2023-06-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0025_delete_customtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_admin_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_admin.business_info')),
            ],
            options={
                'db_table': 'business_admin_token',
            },
        ),
    ]
