# Generated by Django 4.1.4 on 2023-06-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0026_business_admin_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_department',
            name='user',
        ),
        migrations.AddField(
            model_name='business_department',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_admin.business_info'),
        ),
    ]
