# Generated by Django 4.1.4 on 2023-06-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0027_remove_business_department_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_department',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='business_admin.business_info'),
        ),
    ]
