# Generated by Django 4.1.4 on 2023-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0029_business_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
