# Generated by Django 4.1.4 on 2023-07-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0030_alter_business_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='authorized_signatory_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business_info',
            name='licence_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
