# Generated by Django 4.1.4 on 2023-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0033_remove_business_info_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_department',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], max_length=100, null=True),
        ),
    ]
