# Generated by Django 4.1.4 on 2023-07-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0034_business_department_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='area_arabic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business_info',
            name='block_arabic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business_info',
            name='building_name_arabic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business_info',
            name='business_name_arabic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business_info',
            name='office_number_arabic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business_info',
            name='street_name_arabic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
