# Generated by Django 4.1.4 on 2023-07-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0036_business_info_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_department',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='business_admin.business_department'),
        ),
    ]
