# Generated by Django 4.1.4 on 2023-07-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0038_alter_business_info_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_department',
            old_name='parent_id',
            new_name='parent_department_id',
        ),
    ]
