# Generated by Django 4.1.4 on 2023-08-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0040_alter_business_info_authorized_signatory_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='authorized_signatory_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business_info',
            name='licence_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
