# Generated by Django 4.1.4 on 2023-05-01 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('civil_id', models.CharField(max_length=12, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('varified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('address_type', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('email_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
