# Generated by Django 4.1.4 on 2023-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_apartment_number_users_area_users_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house')], default='', max_length=100),
        ),
    ]
