# Generated by Django 4.1.4 on 2023-05-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='language',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nationality',
        ),
    ]
