# Generated by Django 4.1.4 on 2023-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_users_language_users_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='membership',
            field=models.CharField(default='', max_length=100),
        ),
    ]
