# Generated by Django 4.1.4 on 2023-05-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_users_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='membership',
            field=models.CharField(choices=[('free', 'free'), ('basic', 'basic'), ('premium ', 'premium')], default='free', max_length=100),
        ),
    ]
