# Generated by Django 4.1.4 on 2023-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_users_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='membership',
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('individual', 'individual'), ('busniess', 'busniess')], default='', max_length=50),
        ),
    ]
