# Generated by Django 4.1.4 on 2023-05-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0008_alter_packages_package_name_user_membership'),
        ('user', '0009_remove_users_membership_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='membership_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterapp.packages'),
        ),
    ]
