# Generated by Django 4.1.4 on 2023-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_users_membership_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='tothiq_pic'),
        ),
    ]
