# Generated by Django 4.1.4 on 2023-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_users_membership_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='apartment_number',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
