# Generated by Django 4.1.4 on 2023-05-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0012_packages'),
        ('user', '0019_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterapp.language'),
        ),
    ]
