# Generated by Django 4.1.4 on 2023-05-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_users_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_comment_enabled', models.BooleanField(default=True)),
                ('status_change_enabled', models.BooleanField(default=True)),
                ('membership_expiration_enabled', models.BooleanField(default=True)),
                ('user_addon_enabled', models.BooleanField(default=True)),
                ('contract_deletion_enabled', models.BooleanField(default=True)),
                ('contract_review_enabled', models.BooleanField(default=True)),
                ('contract_signature_enabled', models.BooleanField(default=True)),
                ('contract_canceled_enabled', models.BooleanField(default=True)),
                ('new_draft_contract_enabled', models.BooleanField(default=True)),
                ('chat_sound_enabled', models.BooleanField(default=True)),
                ('chat_highlight_enabled', models.BooleanField(default=True)),
                ('reminder_push_enabled', models.BooleanField(default=True)),
                ('reminder_email_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification',
            },
        ),
    ]
