# Generated by Django 4.1.4 on 2023-06-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_notification_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_comment', 'Get notification for new comments.'), ('status_change', 'Get notification for status changes.'), ('membership_expiration', 'Get notification for membership expriration.'), ('user_addition', 'Get notification for users add on.'), ('contract_deletion', 'Get Notification on deleting contract.'), ('contract_review', 'Get notification on reviewed contract.'), ('contract_signature', 'Get notification on signature.'), ('contract_cancellation', 'Get notification on cancted contract.'), ('new_draft_contract', 'Get notification on new or draft contract.')], default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
