# Generated by Django 4.1.4 on 2023-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chat_highlight_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='chat_sound_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='contract_canceled_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='contract_deletion_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='contract_review_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='contract_signature_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='membership_expiration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='new_comment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='new_draft_contract_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='reminder_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='reminder_push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='status_change_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='user_addon_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='user_notification',
        ),
    ]
