# Generated by Django 4.1.4 on 2023-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_users_chat_highlight_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.AddField(
            model_name='users',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('individual_user', 'Individual User'), ('business_user', 'Business User'), ('business_admin', 'Business Admin'), ('super_admin', 'Super Admin')], max_length=255),
        ),
    ]
