# Generated by Django 4.1.4 on 2023-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='device_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='firebase_token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='udid',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
