# Generated by Django 4.1.4 on 2023-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_users_device_type_users_firebase_token_users_udid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='device_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='udid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
