# Generated by Django 4.1.4 on 2023-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_users_device_type_alter_users_firebase_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_type',
            field=models.CharField(choices=[('individual_user', 'Individual User'), ('business_user', 'Business User'), ('business_admin', 'Business Admin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('individual_user', 'Individual User'), ('business_user', 'Business User'), ('business_admin', 'Business Admin')], max_length=255),
        ),
    ]
