# Generated by Django 4.1.4 on 2023-06-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
