# Generated by Django 4.1.4 on 2023-06-19 06:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_notification_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address_type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='apartment_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='area',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='block',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_highlight_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='chat_sound_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='civil_id',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contract_canceled_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contract_deletion_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contract_review_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='contract_signature_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_verified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='membership_expiration_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='new_comment_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='new_draft_contract_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='reminder_email_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='reminder_push_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status_change_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='street_name_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_addon_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
