# Generated by Django 4.1.4 on 2023-06-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_users_tothiq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tothiq_id',
        ),
    ]
