# Generated by Django 4.1.4 on 2023-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_remove_users_tothiq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='membership_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
