# Generated by Django 4.1.4 on 2023-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_users_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='membership_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=50, null=True),
        ),
    ]
