# Generated by Django 4.1.4 on 2023-06-25 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_users_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='civil_id',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
