# Generated by Django 4.1.4 on 2023-06-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='invite_users',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='review_comment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sign_contract',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='upload_document',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='view_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
