# Generated by Django 4.1.4 on 2023-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_users_invite_users_users_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hawati_verification',
            field=models.BooleanField(default=False),
        ),
    ]
