# Generated by Django 4.1.4 on 2023-06-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_users_hawati_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
