# Generated by Django 4.1.4 on 2023-07-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contract_report',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='financial_report',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='super_user_full_access',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
