# Generated by Django 4.1.4 on 2023-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_users_contract_report_users_financial_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='inactive', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
