# Generated by Django 4.1.4 on 2023-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_users_active_status_alter_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='membership_expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
