# Generated by Django 3.2.19 on 2023-09-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='signature_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
