# Generated by Django 3.2.19 on 2023-09-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0074_auto_20230907_1150'),
        ('user', '0058_auto_20230908_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_id', to='contracts.contracts'),
        ),
    ]
