# Generated by Django 3.2.19 on 2023-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_notification_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
