# Generated by Django 3.2.19 on 2023-09-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_user_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_arabic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
