# Generated by Django 3.2.19 on 2023-09-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_auto_20230920_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
