# Generated by Django 3.2.19 on 2023-09-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin_app', '0007_email_template_email_content_arabic'),
        ('user', '0064_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='general_notification_id',
            field=models.ForeignKey(blank=True, db_column='general_notification_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin_app.generalnotification'),
        ),
    ]
