# Generated by Django 3.2.19 on 2023-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_auto_20230926_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='membership_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='Free', max_length=50, null=True),
        ),
    ]
