# Generated by Django 3.2.19 on 2023-09-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_users_tothiq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tothiq_id',
        ),
    ]
