# Generated by Django 3.2.19 on 2023-09-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_remove_users_tothiq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tothiq_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
