# Generated by Django 3.2.19 on 2023-09-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0068_auto_20230926_1007'),
        ('user', '0072_alter_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nationality',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterapp.nationality_type'),
        ),
    ]
