# Generated by Django 3.2.19 on 2023-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_alter_users_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='apartment_number_arabic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='block_arabic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='floor_arabic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
