# Generated by Django 3.2.19 on 2023-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20230927_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender_arabic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
